COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_SRCDIRS := src wolfcrypt/src

CFLAGS += -DNO_WRITEV -DDEBUG_WOLFSSL -DNO_FILESYSTEM -DHAVE_ECC -DHAVE_AESGCM -DWOLFSSL_HAVE_SP_DH -DWOLFSSL_HAVE_SP_ECC -DWOLFSSL_HAVE_SP_RSA -DNO_DEV_RANDOM